site_name: em_inspection
site_description: "Interactive inspection and processing of SBEM datasets"
site_author: "Tomáš Gancarčik"
site_url: "https://ganctom.github.io/em_inspection/"
repo_url: "https://github.com/ganctom/em_inspection"
repo_name: "ganctom/em_inspection"

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
